---
title: End-to-end marine modelling reveals the importance of divergent future upwelling projections for the Southern Benguela Upwelling ecosystem.

author:
  - name: Benjamin T. Grier
    email: bengrier1@outlook.com
    affiliations:
        - ref: UStrath
    attributes:
        corresponding: true
  - name: Matthew Hatton
    affiliations:
        - ref: UStrath
  - name: Lee de Mora
    affiliations:
        - ref: PML
  - name: Yuri Artioli
    affiliations:
        - ref: PML
  - name: Kelly Ortega-Cisneros
    affiliations:
        - ref: MAR
        - ref: NTC
  - name: Douglas C. Speirs
    affiliations:
        - ref: UStrath
  - name: Michael R. Heath
    affiliations:
        - ref: UStrath
  - name: Jack H. Laverick
    affiliations:
        - ref: UStrath

affiliations:
  - id: UStrath
    name: University of Strathclyde, Glasgow, United Kingdom
  - id: PML
    name: Plymouth Marine Laboratory, Plymouth, United Kingdom
  - id: MAR
    name: Marine and Antarctic Research for Innovation and Sustainability, Department of Biological Sciences, University of Cape Town, Cape Town, South Africa
  - id: NTC
    name: Nansen-Tutu Centre for Marine Environmental Research, Department of Oceanography, University of Cape Town, Cape Town, South Africa

abstract: |
    Climate change is projected to alter marine ecosystem structure and function 
    globally. Modelling these changes is challenging, partly because projections 
    of the future physical environment are uncertain, especially in highly 
    productive, and variable, ocean upwelling areas such as the Southern Benguela 
    Upwelling System (SBUS) off southern Africa. Here, the StrathE2E end-to-end ecosystem model is implemented for the SBUS. The model was forced 
    by a four-member ensemble of NEMO-ERSEM physical-biogeochemical model outputs. 
    The ensemble covers two different NEMO-ERSEM forcing models (CNRM-CM6-1-HR & 
    GFDL-ESM4) which provided driving data sets (2010 – 2069) for NEMO, each under
    two Shared Socioeconomic Pathway (SSP) and Relative Concentration Pathway (RCP)
    emissions scenarios (1-2.6: Sustainability – Taking the Green Road, and 3-7.0:
    Regional Rivalry – A Rocky Road).
    
    Net primary production and low trophic level guilds, such as zooplankton, 
    exhibit strongly diverging trajectories across the two NEMO-ERSEM forcing models. High 
    trophic level guilds such as birds, pinnipeds, and cetaceans are highly 
    sensitive to the parameterization of demersal fish, suggesting improvements 
    in our understanding and representation of demersal fish in the region are important for 
    understanding and modelling the impacts of climate change on high trophic 
    level guilds. Environmental driver sensitivity analyses reveal that vertical mixing
    is highly important for variation in low trophic level guilds across these 
    forcing models. These findings highlight the well-recognised sensitivity of the SBUS ecosystem
    to variation in wind-driven upwelling and downwelling, and especially the 
    need for advancements in monitoring and modelling of upwelling changes for 
    the region.

keywords:
    - StrathE2E2

filters:
    - _extensions/authors-block

date: last-modified

format:
  elsevier-docx:
    journal:
      name: Ecological Modelling
      formatting: preprint
      cite-style: authoryear

bibliography: references.bib
csl: oxford-journals-scimed-author-date-ices.csl
engine: julia

crossref:
  custom:
  - kind: float
    reference-prefix: Figure S
    key: sfig
  - kind: float
    reference-prefix: Table S
    key: stbl

editor:
  markdown:
    wrap: 92
    canonical: true
---

# Introduction

The Southern Benguela Upwelling System (SBUS) is a large Eastern Boundary Upwelling System
(EBUS) that extends around the western coast of South Africa, from the warm Agulhas current
in the south to the northern Benguela system (Namibia). The SBUS supports highly productive
recreational and large and small scale commercial fisheries [@hutchings2009; @sumaila2016].
In particular, small-pelagic and Cape Hake fisheries represent substantial food and
employment provisioning for South Africa [@statuso2023; @kainge2020].

Primary and fisheries production in the Southern Benguela exhibit high seasonal and decadal
variability due to changes in environmental conditions such as temperature and upwelling
[@lamont2014; @vandersleen2018]. Phytoplankton, the food-web base, experiences strong
bottom-up control, responding to upwelling and retention of nutrient-rich water on the
shallow shelf [@flynn2020; @martin2024; @cury2004]. Future conditions in EBUS under climate
change are highly uncertain due to a limited understanding of how, and by what magnitude,
wind-driven upwelling processes, and associated temperature and nutrient conditions, may
change [@bograd2023].

Southern Benguela ecosystem modelling under future climate change conditions has primarily
focused on the effects of temperature and primary production on the ecosystem
[@lockerbie2019; @ortega-cisneros2026; @eddy2025], with end-to-end modelling also
incorporating upwelling into forcing [@travers-trolet2014; @ortega-cisneros2018]. While
modelling approaches differ in their projections, multiple studies project declines in
ecosystem biomass, and associated fisheries yield, under increasing temperatures with
differing direction and magnitude of responses across functional groups
[@ortega-cisneros2026; @eddy2025]. Additionally, previous modelling studies show diversity
in ecosystem response to changes in upwelling [@ortega-cisneros2018; @travers-trolet2014;
@ortega-cisneros2018a]. Previous explorations of ecological responses using mechanistic
models focus on few key environmental variables and limited environmental interactions,
possibly reducing the scope of effects seen under explored simulations.

Understanding the influence of multiple climate drivers, and their interactions, on
ecologically and economically important guilds remains an important step towards mechanistic
projections of ecosystem functioning and services [@cooley2023]. End-to-end ecosystem models
holistically represent physical, chemical and biological processes driving climate change
responses. However, increased model and forcing complexity increases the difficulty of
quantifying driver effects, leading to simulations that incorporate limited drivers and
their interactions. Variance-based Shapley Effects originate from game theory [@shapley1953]
and quantify the contribution of input variable variance to output variance while accounting
for non-linear interactions between inputs [@song2016]. Combining these modelling and
analytical approaches can identify key drivers of model outputs, while accounting for high
levels of environmental and ecological complexity.

This investigation aims to further assess the potential impacts of climate change on SBUS
ecosystem state. StrathE2E, a computationally efficient end-to-end ecosystem modelling
framework that acheives sub-minute simulations and accessible parallelism supports a
full-factorial environmental forcing simulation design. Utilizing Shapley Effects, this
investigation aims to identify causal relationships between environmental drivers, ecosystem
state and uncertainty, while accounting for holistic environmental interactions. Quantifying
the relative importance of environmental drivers and their uncertainty for various
aggregated functional groups may help refine regional modelling and monitoring efforts,
enhancing future mechanistic projections of the ecosystem under climate change
[@cooley2023].

# Methods

## Project overview

This investigation uses the StrathE2E end-to-end ecosystem model (**Box 1**). To assess
potential impacts of climate change on the Southern Benguela Upwelling System, environmental
forcing data were extracted from NEMO-ERSEM outputs across six decades (2010-2069), two
Shared-Socioeconomic Pathways (SSPs 1-2.6 and 3-7.0) and two NEMO-ERSEM forcing models
[@artioli2023; @butenschön2016; @gurvan2019]. To identify key drivers of guild mass under
climate change, full-factorial permutation sensitivity analyses are used
(@fig-method-outline; B), first across decades and second across NEMO-ERSEM forcing models.
Variance-based Shapley Effect values quantify variable contributions to guild mass variance
across permutations.

In all analyses StrathE2E models were run for a 49 year spin-up period to stabilize before
extracting final year (i.e. year 50) outputs. Simulations were performed using the R
programming language [@rcore2025] and the StrathE2E2 package [@heath2021]. Subsequent
analyses were conducted using the Julia programming language and Makie visualization system
[@bezanson2017; @danisch2021]. Investigation code can be found at Grier [-@grier2026].

## Box 1: StrathE2E Marine Ecosystem Model Description

StrathE2E combines a dynamic model of marine ecology and a static model of fishing activity,
coded as a package for the R computing environment (Heath et al. 2021). The ecology model is
a set of coupled ordinary differential equations representing the continuous-time rates of
change in nitrogen mass of 26 non-living and living guilds of material due to flows through
a food web network. The guilds span dissolved inorganic nutrient, detritus and microbes,
through classes of plankton, benthos and fish to birds and mammals. The flows represent
predation, food assimilation, metabolism, excretion, demographic transitions (for fish and
benthos guilds; spawning and recruitment), passive advection, active migrations, and fishery
harvest. The spatial resolution is coarse, in keeping with the guild granularity of the food
web - an “inshore” and “offshore” zone, linked by advection and migration. Each zone is
further subdivided into 4 seabed habitats and, in the offshore zone, 2 water column layers.
The seabed habitats are biogeochemical compartments with discrete rates of processing
detritus mineralization and nutrient recycling constrained by sediment grain size, and the
sensitivity of these to disturbance e.g. by fishing abrasion. External environmental drivers
are monthly resolution annual cycles of time-varying physical and chemical data
(temperatures, marine hydrodynamics and river hydrology, sea surface light, turbidity, and
boundary data on inorganic nutrient concentrations and volumetric fluxes of water). The
model outputs state variable nitrogen masses of each guild in each compartment and the flows
between them, at daily intervals.

The StrathE2E fishing model integrates externally defined properties of up to 12 fishing
*métiers* - groups of vessels defined by the fishing gears they use - which selectively
harvest distinctive sets of guilds in the ecology model. Properties of each *métier* are
their habitat-level spatial distributions of activity rate, selectivity for ecology model
guilds, discarding, offal generation and seabed abrasion rates. The outputs from the fishing
model are integrated zone and guild-level fishing mortality, discarding and offal generation
rates, and habitat-level seabed abrasion rates. These are injected as parameters into the
ecology model and assumed to remain constant over all upcoming years of simulation.

## Model domain and spatial compartments

This investigation models the SBUS, extending from the northern South Africa Exclusive
Economic Zone (EEZ) border along the west coast to the Agulhas Bank in the south
(@fig-habitat-map). The Agulhas Current is a warm-water Western Boundary current that flows
southwards along the eastern coast of Southern Africa. The Benguela is an upwelling area
characterized by the cool Benguela Current that flows northward along the western coast.
This creates distinct environmental conditions to the east and west of the Agulhas Bank
[@lutjeharms2006], while injection of warm Agulhas water into the southern part of the
Benguela enhances mixing [@veitch2017]. For more information on model domain designation,
see Supplementary File 2: Model Domain.

## Environmental driving data

Environmental driving data inputs to StrathE2E are monthly resolution time series, averaged
within decades (a climatology). Data were extracted from the outputs, and inputs, of four
variants of a global, quarter-degree resolution NEMO-ERSEM biogeochemistry model
[@butenschön2016; @gurvan2019; @artioli2023]. Additional driving variables, such as
suspended mineral particulate matter and inshore wave height, had no basis for future
projections and are assumed to have a constant annual cycle in future decades. For
information on all environmental variables and sources see Supplementary File 2: Ecological
drivers.

The four variants were defined by two atmospherically forced climate models (CNRM-CM6-1-HR
and GFDL-ESM4) [@voldoire2019; @dunne2020], and two Shared-Socioeconomic Pathways (SSPs
1-2.6 and 3-7.0) [@oneill2014], which provided inputs to NEMO-ERSEM model runs. SSP1-2.6 was
selected as a climate mitigation scenario, while SSP3-7.0 represented a contrasting
plausible future under increasing future emissions [@hausfather2020]. CNRM-CM6-1-HR and
GFDL-ESM4 were chosen for contrasting climate sensitivity levels. GFDL-ESM4 has an
equilibrium climate sensitivity (ECS) value of 2.7-3.4°C [@dunne2020], while CNRM-CM6-1-HR
has a higher ECS of 4.34°C [@jones2023], meaning CNRM-CM6-1-HR represents a greater level of
atmospheric warming for the same amount of CO2 increase compared to GFDL-ESM4.

## Parameterization for Southern Benguela

To implement StrathE2E (**Box 1**) for the SBUS, region-specific inputs from literature and
regional expert knowledge were collated for the 2010-2019 period where possible
(@stbl-model-inputs). This includes input data representing fishing fleets and their catch
of modelled guilds, biological event timing data for key regional species for each guild and
observational target data for parameter optimization of the ecosystem model
(@stbl-model-inputs). The SBUS model represents 11 regional fishing gear types including
midwater trawl, demersal trawl, purse-seine, nets, pole and line, squid jigs, longlines,
small scale linefishing, commercial West Coast Rock Lobster (*Jasus lalandii*) traps,
recreational fishers and subsistence fishers (Supplementary File 2). Due to limited publicly
available data, reconstructed Sea Around Us data are used to parameterize fishing fleet
catching power levels [@zeller2017]. Reproductive event timing parameters were calculated
using key regional species to represent each guild based on data availability. For more
information on the parameterization of ecological and fisheries model components see
Supplementary File 2 [@grier2026a].

Fitted parameter calibration involved using simulated annealing to seek parameter values
providing maximum likelihood of a suite of empirical 'target' data on ecosystem and
fisheries states during the baseline (2010-2019) calibration period [@heath2021]
(@stbl-model-inputs). StrathE2E models were calibrated individually for CNRM-CM6-1-HR and
GFDL-ESM4 to preserve differing representations of baseline conditions, resulting in a
"CNRM-CM6-1-HR StrathE2E model" and a "GFDL-ESM4 StrathE2E model". For more information on
data sources, parameterization and calibration see Supplementary File 2.

## Projected climate change impacts

Under four possible future scenarios across six decades modelled steady state nitrogen mass
values were averaged across the domain area for each guild. Fishing pressure is held
constant at 2010-2019 levels across all simulations. Monte Carlo simulations were performed
using ecological parameter values randomly sampled from uniform distributions, weighting
model outputs according to observational target data likelihood (see Supplementary File 2
for information on target data) to calculate 95% credible intervals [@heath2021]. Sampled
parameters include all fitted parameters such as diet preferences and nitrogen uptake rates,
as well as fixed parameters such as guild Q~10~ values and background metabolic rates. All
parameters were sampled using a coefficient of variation of 0.15. For each model
parameterization, 1000 parameter combinations were sampled and applied to variants (total
24,000 model runs). Final year steady state outputs are visualized as decadal time series.

To explore ecosystem state variance under climate change, principal component analysis (PCA)
was conducted on best-fit steady state mass values, rotating multivariate guild mass values
along two principal components. The average vector between decade Principal Component (PC)
values and average vector between forcing models in PC space were calculated to identify
guilds contributing strongly to signals of ecosystem PCA variance. Each guild's contribution
was quantified as the angle between guild mass PCA loading and the two variation vectors,
selecting guilds that correlate with across decade and forcing model variation for further
analyses.

## Identifying important climate change drivers

To quantify the influence of environmental driving data on ecosystem state under different
contexts (climate forcing models, SSPs, decades), driver group contributions to ecosystem
outcomes were calculated using full-factorial permutations. Permutation analyses were
informed by biomass PCA results and performed for key signals of projection uncertainty:
firstly, across decades to identify drivers of guilds with strong trends across time and
secondly, across NEMO-ERSEM forcing models to identify drivers of guilds that diverge
between GFDL-ESM4 and CNRM-CM6-1-HR projections. Guilds with a PCA loading angle of less
than 30° to vectors of across decade variance and across NEMO-ERSEM forcing model variance
respectively were selected for analyses. While arbitrary, a 30° threshold was used to focus
analyses and presentation of guilds that contribute to the clearest signals of variance in
overall ecosystem state under changing climate conditions (@sfig-pca-separation). While no
climate driver importance results are presented or discussed for planktivorous fish and
migratory fish, Shapley Effect values for all remaining guilds can be found at
@sfig-across-esm-shap-others and @sfig-across-decade-shap-others. Additionally, Net Primary
Production was included in output analyses to investigate drivers of change in system
productivity.

In StrathE2E, temperature influences the metabolism and prey uptake rates for guilds, while
boundary flows and vertical mixing influence distributions of nitrogen and plankton guilds
across domain boxes, affecting predator distributions and nutrient uptake. Driving variables
were grouped according to @tbl-variable-groups, and then permuted in full-factorial
combinations (@fig-method-outline). Annual mass results were collated for each target guild
to calculate the variance-based Shapley Effect value of each variable for each guild
[@song2016].

| Variables | Driver group | Group description | Group varies across |
|-----------------------|-----------------------|-----------------------|-----------------------|
| sslight | Light | Surface irradiance. | Decade, CMIP6 forcing model, SSP |
| so_temp, d_temp, si_temp | Temperature | Water volume temperatures. | Decade, CMIP6 forcing model, SSP |
| rivervol, rivnitrate, rivammonia, rivdetritus | River outputs | River output volume and nutrient outflow concentrations into surface inshore habitat. | Decade, CMIP6 forcing model, SSP |
| logkvert, d_so_upwelling, so_d_downwelling | Vertical mixing | Upwelling, downwelling and vertical diffusivity between surface and deep offshore water volumes. | Decade, CMIP6 forcing model, SSP |
| domain inflow variables, so_si_flow | Boundary flows | External inflow rates of water into si, so and d water volumes. Movement of water from surface offshore to inshore volumes. | Decade, CMIP6 forcing model, SSP |
| \*\_nitrate, \*\_ammonia, \*\_phyt, \*\_detritus | Volume boundary nutrient concentrations | Ocean boundary nutrient concentrations for each water volume (so, si and d). | Decade, CMIP6 forcing model, SSP |
| so_atmnitrate, so_atmammonia, si_atmnitrate, si_atmammonia | Atmospheric nutrient flux | Deposition rates of nitrate and ammonia into surface water volumes. | Decade, SSP |

: Environmental driving variables used in climate permutation analyses, the groups allocated
to variables, and levels of variation. All other chemistry and physics driving variables are
constant across variants (Supplementary File 2). Abbreviations: "si" refers to the shallow
inshore water volume, "so" refers to the shallow offshore water volume, "d" refers to the
deep (offshore) water volume. {#tbl-variable-groups}

#### Shapley effects

Shapley Values quantify the contribution of a variable to an output value [@shapley1953].
Variance-based Shapley Effects are an extension of Shapley Values, which are a fair way to
calculate the contribution of each variable to variance in a given output [@song2016]. By
calculating the contribution of an input to all possible coalitions of other variables,
Shapley Effects incorporate interactions between variables, using a full factorial
permutation set to calculate exact values. Shapley Effects offer an advancement over common
sensitivity metrics such as first-order effects by effectively incorporating input
interactions [@song2016]. Variance-based Shapley Effects quantify driver group contributions
to guild output variance. For further explanation of Shapley Effect calculations and
permutation runs see Supplementary File 1.

#### Identifying key drivers across decades

Driver groups were permuted across three decades (2010-2019, 2030-2039 and 2060-2069) within
the four climate scenarios (forcing model - SSP combinations). Results are presented for
guilds that are strongly associated with ecosystem variance across decades
(@sfig-pca-separation), and net primary production.

Model permutations were additionally used to identify model runs where combinations of
driver groups are changed to 2060-2069, while other variables remain at a 2010-2019
baseline. These model runs are used to assess the influence of driver group interactions and
prevalence of non-linear interactions between driver groups.

#### Identifying key drivers across NEMO-ERSEM forcing models

Driver groups were permuted across forcing models, within each of the six decades and SSPs
analysed. Permutations are completed once for each model parameterization (CNRM-CM6-1-HR and
GFDL-ESM4 StrathE2E parameterization). Six driver groups vary across NEMO-ERSEM forcing
models, with two sets of values per decade and SSP (@tbl-variable-groups). Results are
presented for guilds strongly associated with ecosystem variance across NEMO-ERSEM forcing
models (@sfig-pca-separation), and net primary production.

# Results

## Future climate impacts

Both CNRM-CM6-1-HR and GFDL-ESM4 StrathE2E models experienced high levels of parameter
uncertainty for mass value predictions (@sfig-biomass-timeseries; @sfig-biomass-pca-mc).
Despite low confidence in absolute mass projections, guilds experience higher confidence for
modelled directions and magnitudes of change under increasing climate pressures
(@fig-percent-biomass-timeseries). Narrow credible intervals on relative climate impacts,
such as for plankton and benthos guilds, suggest that mechanisms of change are not sensitive
to parameter changes. Ecosystem net primary productivity is projected to substantially
increase across decades under GFDL-ESM4 NEMO-ERSEM forcing model
(@fig-percent-biomass-timeseries) and decrease under CNRM-CM6-1-HR forcing model.

Demersal fish, demersal fish larvae, planktivorous fish, birds, pinnipeds and cetaceans are
particularly sensitive to changes in model parameters (@fig-percent-biomass-timeseries),
experiencing broader credible intervals than lower trophic level guilds. Guild production
rates for demersal fish show that modelled demersal fish gain greater nitrogen mass from
recruitment than from consumption, with recruitment sustaining net production at a positive
level (@stbl-dfish-biology). To investigate the influence of demersal fish larvae
parameterization on predatory guilds, a one-at-a-time sensitivity analysis was performed on
physiological parameters: demersal fish larvae density dependent mortality; nitrogen uptake
half-saturation coefficient; and maximum nitrogen uptake rate parameters control biomass
growth and recruitment into adult demersal fish. These parameters were sampled in 100 evenly
spaced steps from -25% to +25% of the base parameter value from CNRM-CM6-1-HR and GFDL-ESM4
models respectively, resulting in 300 runs for each of the two models. Local sensitivity
analyses revealed that planktivorous fish, demersal fish, pinnipeds, birds and cetaceans are
highly sensitive to demersal fish larvae maximum nitrate uptake rate and nitrogen uptake
half-saturation coefficient values (@sfig-dfishlar-sensitivity). Although planktivorous fish
contribute more than demersal fish to nutrient uptake for birds and cetaceans
(@sfig-decade-sep-diet), the high reliance of demersal fish on recruitment and subsequent
sensitivity of adult demersal fish to larval parameterization propagates into high
uncertainty for top predator guilds.

Principal Component Analysis highlights the influence of decadal changes and NEMO-ERSEM
forcing model choice on overall modelled ecosystem masses. The first two principal
components explain 72% of ecosystem mass variance. Benthos Suspension/Deposit Feeders,
Omnivorous zooplankton, surface layer Phytoplankton, total nitrogen mass and Carnivorous
zooplankton align strongly with ecosystem state changes across the forcing models
(@fig-biomass-pca, B; @sfig-pca-separation). Pinnipeds, Demersal fish, deep layer
Phytoplankton, Birds, Benthos Carnivorous/Scavenge Feeders and Cetaceans align strongly with
ecosystem changes across decades (@fig-biomass-pca, B; @sfig-pca-separation). There is
little variation in ecosystem state across SSPs.

## Drivers of temporal ecosystem change

For guilds strongly correlated with temporal ecosystem change, Shapley Effect environmental
driver contribution values indicate that only temperature, boundary flow and vertical mixing
driving variables contribute to variance in modelled mass levels (@fig-across-decade-shap).
When forced by CNRM-CM6-1-HR, under SSP3-7.0 the contribution of temperature to mass
variance increases from SSP1-2.6. Under CNRM-CM6-1-HR, temperature is a stronger driver of
variation for pinnipeds, birds and cetaceans compared to deep layer phytoplankton,
carnivorous/scavenge feeding benthos and demersal fish guilds. When forced by GFDL-ESM4,
three of the six guilds are primarily driven by boundary flows and three are primarily
driven by vertical mixing, with all guilds having low importance of temperature. Deep layer
phytoplankton has distinct Shapley Effect values to other assessed guilds, with \>75% of
variance attributed to vertical mixing under all forcings. Interactions between
environmental driver groups influence guild mass outcomes in an additive manner, suggesting
driver interactions are not influential in the model (@sfig-var-interaction-hist). GFDL-ESM4
forcing data show a greater degree of seasonal variability in vertical diffusivity and
offshore upwelling and downwelling compared to CNRM-CM6-1-HR (@sfig-driver-vertical-mixing).

## Drivers of variance across NEMO-ERSEM forcing models

For guilds correlated with ecosystem state separation across the NEMO-ERSEM forcing models,
Shapley Effect contribution values indicate high contribution from vertical mixing
(@fig-across-esm-shap). Boundary flows have the second highest contribution to
across-forcing model mass variance for almost all guilds assessed. Driver groups such as
nutrient concentrations, river outputs, light and temperature have low contributions. Driver
group contributions are similar across the best-fit CNRM-CM6-1-HR and GFDL-ESM4
parameterizations, highlighting consistent mechanisms of change (@fig-across-esm-shap).

The choice of NEMO-ERSEM CMIP6 model forcing StrathE2E strongly influences projected
ecosystem outcomes (@fig-biomass-pca). The two forcing models project different future wind
fields in the region, resulting in distinct NEMO-ERSEM projections of upwelling and
downwelling (@sfig-driver-vertical-mixing; @sfig-ssp3-winds-cmip). Under these projections,
low trophic level guilds and net primary production display diverging best-fit model
trajectories. Vertical mixing contributes the most (\>60%) to variance for the majority of
these guilds.

# Discussion

StrathE2E modelling for the Southern Benguela ecosystem is consistent with observational and
modelling literature that suggests a strong influence of climate variability and change on
the system [@shannon2009; @blamey2015; @fig-biomass-pca]. There have been contrasting
suggestions about spatially complex long-term upwelling and warming trends experienced in
the Southern Benguela system [@blamey2015; @vanderlingen2018]. Additionally, range shifts in
multiple species have been documented, likely driven by periods of intensified upwelling
[@vanderlingen2018]. While offshore temperatures have increased, periods of coastal cooling
have led to changes in planktivorous fish distributions from the west to the south of South
Africa [@roy2007; @vanderlingen2018]. Ongoing oceanographic monitoring and biogeochemical
modelling (e.g. Oxygen and Biogeochemical Dynamics along the West African Margin;
@mirkin2026), along with validation of climate model behaviour with observed trends may help
to reduce uncertainty in climate and ecosystem model projections for the region.

This investigation identified temperature, vertical mixing and boundary flows as key driver
groups influencing change in high trophic level guilds across decades. @ortega-cisneros2018
modelled the effects of climate change on the ecosystem using an Atlantis end-to-end model
forced by low (RCP 2.6) and high (RCP 8.5) emission futures. Atlantis modelling projected
declines for most functional groups including top predators such as cetaceans, seabirds and
demersal fish including sharks, with temperature being suggested as a strong driver
[@ortega-cisneros2018]. On the other hand, modelling with Atlantis [@ortega-cisneros2018]
and ROMS-N~2~P~2~Z~2~D~2~-OSMOSE [@travers-trolet2014] found that changes in vertical mixing
(under RCP 8.5) did not influence high trophic level guilds. Distinct magnitudes, directions
and mechanisms of change suggest a high influence of structural (ecosystem model)
uncertainty for the Southern Benguela system.

Structural uncertainty arises due to choices made in the construction and implementation of
ecosystem models such as the resolution of components (spatial, temporal, taxonomic) and
relationships/links represented [@payne2016]. @ortega-cisneros2026 quantified uncertainty
across a Southern Benguela ecosystem projection ensemble containing 2 marine ecosystem
models (Atlantis and EwE), and 2 Earth System Models (ESMs) and 2 SSPs used for temperature
and primary production forcing data. @ortega-cisneros2026 found ecosystem model structural
uncertainty accounted for more than 50% of projection variance for groups such as demersal
fish and zooplankton, with uncertainty between ESMs also contributing substantially to
variance across groups. @eddy2025 found strong divergence in overall biomass projections for
the system across regional ecosystem models (Atlantis and EwE). While results of this
investigation find substantial contribution of NEMO-ERSEM forcing models to uncertainty
(@fig-biomass-pca), we also find strong contribution of parameter uncertainty, which was
previously limited in its consideration [@ortega-cisneros2018a; @ortega-cisneros2026;
@eddy2025] (@fig-percent-biomass-timeseries; @sfig-biomass-pca-mc). @ortega-cisneros2018a
found limited influence of phytoplankton growth parameters on ecosystem state, with only
Anchovy and small phytoplankton guilds showing substantial responses. Incorporating
StrathE2E into a three model ensemble with Atlantis and EwE to quantify parameter,
structural, and scenario uncertainty would further enhance model development and decision
support.

Identification of vertical mixing as the primary driver of low trophic level guild variance
is supported by literature suggesting that bottom-up control leads to high variability
across spatial and temporal scales due to upwelling [@cury2004; @martin2024; @lamont2014].
There is little consensus on how this ecosystem, and other EBUS globally, may change in the
future due to high levels of uncertainty around future upwelling [@bograd2023;
@garcía-reyes2015]. In a global comparison of EBUS NPP projections (including the Southern
Benguela) using 13 CMIP6 models, @cioffi2025 found that differences in upwelling-favourable
winds resulted in substantial variation in both direction and magnitude of NPP projections.
These conclusions are supported by the results of this investigation (@sfig-ssp3-winds-cmip;
@sfig-driver-vertical-mixing; @fig-percent-biomass-timeseries). A formal
assessment/validation of NEMO-ERSEM's representation of upwelling, along with validation of
wind projections obtained from climate models are necessary to improve confidence in
subsequent ecosystem model applications in EBUS regions.

In the face of high uncertainty and diverging projections, climate change impact
investigations would benefit from comparisons of a broad range of ecosystem models, model
parameterizations, and environmental forcing scenarios [@eddy2025; @maury2025; @murphy2025].
Approaches such as Decision Making Under Deep Uncertainty involve exploring many possible
ecosystem futures, helping to identify trajectories of environmental conditions, ecosystem
responses or management decisions that may lead to critical outcomes [@kalra2014]. Exploring
a broader range of futures (forcing models and SSPs) could help to identify critical
patterns of upwelling that may lead to poor ecosystem states, allowing the focusing of
monitoring and trend assessment efforts.

| Guilds | Driving sources of uncertainty | Future actions |
|-------------------------------|-------------------------------|-------------------------------|
| Planktivorous fish, demersal fish, birds, pinnipeds and cetaceans | Demersal fish parameterization | Improved data availability to support ecological parameterization of demersal fish guild, and improved aggregation of regional species into functional guild |
| Phytoplankton and zooplankton guilds, and Net Primary Production | Vertical mixing forcing due to CMIP6 forcing model wind projections | Improvements to understanding of local upwelling trends and validation of biogeochemical model responses |

: Summary of key sources of uncertainty for ecosystem guilds based on StrathE2E modelling.
Includes lists of relevant guilds, the sources of uncertainty influencing the guilds and
possible future actions that could be (or are being) taken to address these uncertainties.
{#tbl-guild-uncertainties}

The results of this investigation highlight ecosystem components and drivers that should be
prioritized for further investigation (@tbl-guild-uncertainties). Greater parameter
uncertainty than future scenario uncertainty, for high trophic level guilds in particular,
suggests data collection and model selection are important areas of focus. Additionally,
improved understanding and projection of wind-driven upwelling trends under climate change
will be important for projecting ecosystem state into the future, particularly for low
trophic level guilds. Approaches such as near-term ecological forecasting may offer a
pathway to iteratively incorporate such advancements in ecological and climate change
understanding in the region at timescales relevant to management decisions (see Sustainable
Ocean Modelling Initiative: A South African Approach (SOMISANA); https://somisana.ac.za)
[@dietze2024].

This investigation uses StrathE2E as an experimental system, representing important physical
and ecological processes, and exploratory analyses to complement higher resolution models
used for direct decision-support [@espinoza-tenorio2012]. The computational advantages of
reduced model complexity allow for comprehensive analyses and the identification of key
system drivers at a strategic level in this study. Additionally, the strategic use of
uncertainty analyses allows the identification and prioritization of knowledge gaps. Our
work therefore supports the ongoing development of tactical tools dedicated to specific
management applications, rather than informing this level of decision-making directly
[@geary2020; @jakeman2024].

## Limitations

High parameter uncertainty in the presented models may be due to biased or inconsistent
target data used for fitting [@hilborn1992]. Additionally, identifying best-fit parameter
values increases in difficulty as model complexity increases [@preston2025].
@ortega-cisneros2018 provided error estimates across subsets of Atlantis parameters
controlling plankton guilds' growth rates, however computational limitations prevented a
quantification of global parameter uncertainty. This investigation advances application of
global parameter uncertainty quantification for end-to-end ecosystem models in the southern
Benguela. While parameter uncertainty decreases forecast precision, this may not prevent
effective decision support but requires the use of alternative methods such as evaluation of
management outcome distributions using models purposefully built for specific management
applications [@ascough2008; @reichert2005; @jakeman2024].

While parameterized using data spanning 2010-2019 where possible, target data for guild
production rates and P:B ratios were sourced from ecological models of the 1978-2015 period
that used departmental survey data to model fisheries [@shannon2020]. This investigation
used reconstructed fisheries data for the 2010-2019 period from Sea Around Us [@zeller2017]
with domestic fleet uncertainty scores ranging from "low" ($\frac{+}{-}$ 30%) to "very low"
($\frac{+}{-}$ 50%) (@sfig-sau-uncertainty). Reconstructed total catch timeseries for
Sardines, Anchovies, Round Herring and Cape Hakes closely match those reported in
@statuso2023. Improved completeness and quality of parameterization and calibration data may
help to reduce parameter uncertainty and improve the representation of guilds in the model.
For more information on the parameterization process see Supplementary File 2.

Interpretation of demersal fish and top-predator guilds, such as birds, pinnipeds and
cetaceans, using these StrathE2E implementations must consider that demersal fish biological
event timing parameters reflect available literature for Cape Hake species (*Merluccius
capensis* and *Merluccius paradoxus*) only (Supplementary File 2). It has been suggested
that Cape Hake in the northern Benguela region (Namibia) experience high annual variability
in stock biomass [@macpherson1991] driven by variable recruitment [@kainge2013]. This likely
reflects the sensitive parameterization of demersal fish in the Southern Benguela models
presented. Similarly, due to limited data availability, the parameterization of
planktivorous fish, suspension/deposit feeding benthos and carnivorous/scavenge feeding
benthos guilds used 'indicative' regional species to represent guild reproduction event
timings (Supplementary File 2: Event timing parameters). The choice of species used to
parameterize these guilds' biological processes may affect results and should be considered
when interpreting conclusions. Further investigations would benefit from global parameter
uncertainty decomposition, such as sensitivity analyses, applied across guilds, to identify
additional sources of uncertainty and areas for model improvement.

While this investigation does not find high overall importance of projected temperature
changes for modelled guilds, previous studies found a storng influence of temperature on the
ecosystem [@ortega-cisneros2018; @statuso2023]. Reduced temperature importance may be due to
the use of Q~10~ temperature coefficient values from teh North Sea StrathE2E implementation
[@heath2021]. Q~10~ temperature coefficients parameterize the relationship between
tempertaure and feeding and metabolic rates, thus directly affecting guild production and
biomass. Additionally, Q~10~ values are not guild specific, instead different values are
used for autotroph metabolism, heterotroph feeding and heterotroph metabolism. Improved
representation of temperature effects, including chronic temperature change and extreme
events, may improve StrathE2E climate impact projections and is the subject of ongoing
research.

## Future work

While improved calibration data can increase model forecast precision, validation with
independent data, particularly for responses to climate change, can improve confidence for
decision makers [@lubianabotelho2025]. @ortega-cisneros2017 performed hindcast skill
assessment of a regional Atlantis model, identifying variable performance across modelled
species, however data independent of model calibration was not available. Subject to data
availability, validation of the best-fit southern Benguela StrathE2E models presented in
this investigation using observational data independent of the data used for model
calibration would improve confidence in the presented conclusions and ecosystem projections.

Observational studies have suggested that trends in fishing in the region may interact with
climate change driven environmental trends in the region, altering the hazards experienced
by species [@jarre2015; @ramírez2022]. While this investigation found little evidence for
influence of non-linear interactions between environmental driving groups, previous
end-to-end modelling has found evidence for non-linear interactions between environmental
and fishing drivers [@travers-trolet2014; @ortega-cisneros2018]. Using a protocol such as
Ocean System Pathways (developed by FishMIP - the Fisheries and Marine Ecosystems Model
Intercomparison Project), which outlines a standardized approach for modelling the influence
of future climate change and fisheries trends on marine ecosystems would allow StrathE2E to
contribute to valuable model intercomparison investigations for this highly variable region
[@maury2025].

## Conclusion

This investigation uses StrathE2E models to explore possible consequences of future climate
change on the Southern Benguela Upwelling ecosystem. Climate change sensitivity analyses
reveal a strong influence of vertical mixing, particularly for low trophic level guilds.
Future scenario uncertainty (due to uncertain projections of upwelling related winds)
strongly influences future ecosystem projections, identifying a key area for improved
monitoring and modelling. While this investigation reveals that temperature, vertical mixing
and boundary flows may be important for high trophic level guilds, high parameter
uncertainty and sensitivity are present. Sensitivity to demersal fish parameterization
highlights where improvements in the representation and parameterization of guilds, as well
as observational calibration data, would improve understanding and projection of climate
change impacts. Inter-comparisons of regional ecosystem models under climate change,
focusing on mechanisms of climate impacts will be valuable to reduce uncertainty and
understanding of future change.

# Acknowledgements

The authors would like to acknowledge and thank Lynne Shannon for their contribution to data
collation and discussions during model implementation and comments and discussion during
manuscript revision. The authors would like to acknowledge and thank Stephen Holness and
Tracey Pamela Mc Gahey for their assistance with spatial fishing intensity data.

# CRediT Statement

**Benjamin Grier:** conceptualisation, data curation, formal analysis, investigation,
methodology, software, validation, visualisation, writing - original draft, writing - review
and editing. **Matthew Hatton:** methodology, software, writing - review and editing. **Lee
de Mora:** data curation, visualisation, writing - review and editing. **Yuri Artioli:**
data curation, visualisation, writing - review and editing. **Kelly Ortega-Cisneros:** data
curation, writing - review and editing. **Douglas Speirs:** conceptualisation, funding
acquisition, software, supervision, writing - review and editing. **Michael Heath:**
conceptualisation, data curation, funding acquisition, resources, software, supervision,
validation, writing - review and editing. **Jack Laverick:** conceptualisation, data
curation, software, supervision, validation, writing - review and editing.

# Conflict of Interest Statement

The authors declare no conflicts of interest.

# Data Availability Statement

The full reproducible investigation and links to required data sources can be found at
@grier2026 (<https://doi.org/10.5281/zenodo.19751528>). StrathE2E model files for the
Southern Benguela implementation can be found at @grier2026a
(<https://doi.org/10.5281/zenodo.19868227>).

# Funding Statement

This project has received funding from the European Union's Horizon 2020 research and
innovation programme under Grant Agreement No 862428 (MISSION ATLANTIC). This output
reflects only the author's view and the Research Executive Agency (REA) cannot be held
responsible for any use that may be made of the information contained therein.

# References

::: {#refs}
:::

# Figures

![Overview of methodology used to address the two overarching investigation aims. **Panel
A** represents the first aim: *to assess potential future climate impacts for the Southern
Benguela Upwelling ecosystem*. Projecting ecosystem state using StrathE2E models and 24
unique sets of driving data (31 variables; see @tbl-variable-groups) across decades,
NEMO-ERSEM forcing models from the Sixth phase of the Coupled Model Intercomparison Project
(CMIP6), and Shared Socioeconomic pathways (SSPs) [@artioli2023]. **Panel B** represents the
second overarching aim: *to identify key drivers of ecosystem state change under climate
pressure, including drivers of variance across decades and drivers across projected future
trajectories*. Panel B includes a hypothetical example of a climate permutation sensitivity
analysis where variable values are drawn from three different datasets. In this example 3
data sources and 4 variables create a permutation set of 81 ($3^4$) total model runs. In our
investigation climate sensitivity analyses are performed to capture variance (i) across
decades and (ii) across NEMO-ERSEM forcing
models.](../figs/StrathE2E_paper_method_outline.png){#fig-method-outline}

![Model habitat map indicating the domain region and the distinct model habitat types for
inshore and offshore regions that are used to distribute fishing effort. Habitat types
include rock, gravel, sand and mud [@birch1987; @skowno2019]. The inshore region encompasses
areas of less than 50m depth that are within 20km of the shore. The offshore region extends
to areas of the continental shelf that have a depth of 800m and is comprized of a shallow
(0-50m) and deep volume (50-800m).](../figs/habitat_map.png){#fig-habitat-map
width="14.82cm"}

![Final year, whole-domain percentage change in mass for each decade of forcing data under
each future scenario, relative to 2010-2019 levels. The y axis represents the change in
final year mass as a percentage of 2010-2019 mass for each guild. The x axis represents the
modelled decades. The line colours represent the two climate models, GFDL-ESM4 in blue and
CNRM-CM6-1-HR in yellow. Line-styles represent the two Shared Socio-Economic Pathways,
SSP1-2.6 with solid lines and SSP3-7.0 with dashed lines. Bold lines represent the best-fit
parameterization outputs. Transparent bands represent the 95% credible intervals for
percentage change values obtained from Monte Carlo simulations. Percentage change in total
nitrogen mass is not sensitive to the represented changes in parameter
values.](../figs/initial_cc_assessment/percent_biomass_timeseries_mc.png){#fig-percent-biomass-timeseries
width="14.82cm"}

![Panel A: PCA results for final year guild mass conditions for each decade of forcing data
under each future scenario and NEMO-ERSEM forcing model. The line colours represent the two
climate models, GFDL-ESM4 in blue and CNRM-CM6-1-HR in yellow. Line-styles represent the two
Shared Socio-Economic Pathways, SSP1-2.6 with solid lines and SSP3-7.0 with dashed lines.
Dot points represent 2010-2019 decade of forcing, and arrowheads represent the 2060-2069
decade of forcing. Panel B: PCA axis loadings for each of the guild mass state variables,
labelled with letters. Red and blue dashed lines represent the average direction of change
in PC values across NEMO-ERSEM forcing models and decades respectively. Guilds that align
strongly with a dashed line in panel B can be considered to contribute strongly to
directional variance in panel
A.](../figs/initial_cc_assessment/biomass_pca.png){#fig-biomass-pca width="14.82cm"}

![Shapley Effect contribution values for guilds identified as being strongly correlated with
ecosystem state change over time (@sfig-pca-separation) under each forcing model - SSP
scenario. Bars represent the contribution of each driver group to guild mass variance, with
a value of 1 representing explanation of 100% of guild variance. Variables are represented
by different colours, with a lack of colour indicating no contribution of output variance
(no contribution from light, river outputs, nutrient concentrations or atmospheric nutrient
flux driver groups). Blue bars indicate the contribution of boundary flow variables; orange
bars represent the contribution of temperature variables and green bars indicate the
contribution of vertical mixing variables to guild output
variance.](../figs/across_decade_permutations/important_guild_shapley.png){#fig-across-decade-shap
width="14.82cm"}

![Shapley Effect contribution values for guilds identified as being strongly correlated with
differences in ecosystem state across the NEMO-ERSEM forcing models (@sfig-pca-separation),
for each StrathE2E parameterization. Points represent the median Shapley Effect value for
each guild and driver group across the combinations of two SSPs and six decades. Error bars
represent the interquartile range of Shapley Effect values for each guild and variable
group. As median and interquartile range values are displayed, effects for a guild may not
sum to 1.](../figs/across_esm_permutations/median_shapley_effects.png){#fig-across-esm-shap
width="14.82cm"}

# Supplementary Material

The following supplementary material is available at *ICESJMS* online.

**Supplementary File 1:** Document containing additional figures and tables referred to in
the text related to the parameterization of StrathE2E for the Southern Benguela system and
additional supporting results for this investigation.

**Supplementary File 2:** Detailed document describing the process followed and data sources
used for the parameterization of the Southern Benguela StrathE2E models.

## Model parameterization

::: {#stbl-model-inputs}
| Source | Model Inputs | Time Period |
|-----------------------------------|------------------------|---------------------------------|
| Sea Around Us - fishing catch data [@zeller2017] | Catch data separated into catch power (catch/activity) and discard rates | Parameterized with 2010-2019 data |
| South Africa National Biodiversity Institute - spatial fishing pressure data [@holness2018; @skowno2019] | Spatial distribution of fishing fleet activity | 2018 - layers finalized 2025 |
| Regional expert collaboration - target data | Fitting target data | 1978-2015 |
| World Ocean Atlas 2023 - monthly nitrate concentration data | Fitting target data | 2023 |
| Literature | Fishing fleet annual effort estimates, biological event timings | Parameterized using 2010-2019 literature, or nearest available time period values. Additional details can be found in Supplementary File 2 |

: Data sources used for parameterization of the 2010-2019 Southern Benguela StrathE2E model
and the model inputs that each data source contributed to. Full information for the
implementation process and processing and use of each data source can be found at
Supplementary File 2.
:::

![Barplot showing the proportion of guild landings for each guild that are allocated to Sea
Around Us uncertainty scores. Low values represent data with greater certainty. Blue areas
represent data with a "very low" score ($+/-$ 50%) and yellow areas represent data with a
"low" score ($+/-$ 30%) [@zeller2017]. "Missing" uncertainty scores are represented in green
and indicate where no score was recorded for data. Data with a "missing" uncertainty score
are largely "Assigned Tuna RFMO catch", including catch from countries other than South
Africa.](../figs/SAU_landings_uncertainty.png){#sfig-sau-uncertainty width="14.82cm"}

## Shapley Effects

The following equations were used to calculate variance-based Shapley Effects
[@eq-shapleyvalue; @shapley1953; @song2016], quantifying the contribution of driver groups
to variance in guild outputs. $$
\phi_j(val) = \sum_{S \subseteq \{1,\ldots,p\}\setminus\{j\}} 
   \frac{|S|!(p-|S|-1)!}{p!}\,\big(val(S \cup \{j\}) - val(S)\big)
$$ {#eq-shapleyvalue}

Where $\phi_j$ is the Shapley value for variable $j$, $S$ is a subset of input variables not
including $j$, $p$ is the number of possible coalitions of variables that do not include
$j$. To extend this calculation to variance-based Shapley Effects [@song2016] on discrete
inputs (levels = model variants), $val(S)$ is substituted for [@eq-varexplained; @song2016],
calculating the output variance explained by inputs from a set of variables $S$. The
resulting Shapley Effect ($\phi_j$) represents the sum of marginal contributions of variable
$j$ to all coalitions of other input variables. By calculating the contribution of $j$ to
all possible coalitions of other variables, Shapley Effects incorporate the interactions
between variables, using a full factorial permutation set to calculate exact Shapley
Effects.

$$
Var[E[Y|X_S]]
$$ {#eq-varexplained}

@eq-varexplained is used to calculate the variance in conditional means of output $Y$ across
levels of inputs from input set $X_S$.

To calculate driver group Shapley Effect values for guilds, model outputs must be collated
from model permutations. Model permutations (runs) must include all possible coalitions of
driver group data sources (@fig-method-outline; @tbl-variable-groups). To calculate the
number of model permutations required for full-factorial simulations, @eq-permutation-number
can be used.

$$
N = d ^ v * r
$$ {#eq-permutation-number}

Where $d$ is the number of data sources available for permutation, $v$ is the number of
driver groups being permuted across data sources, and $r$ is the number of independent
replication levels. For across-decade permutations, there are 3 decades in the dataset
($d$), 7 driver groups being permuted ($v$) and 4 climate scenario replications ($r$)
(NEMO-ERSEM forcing models and SSPs), resulting in a total of 8,748 model runs. For
permutations across NEMO-ERSEM forcing models, there are 2 forcing models in the dataset
($d$), 6 driver groups being permuted across them ($v$), and 24 replication levels formed by
6 decades, 2 SSPs and 2 model parameterizations, resulting in a total 1,536 model runs.

## Supplementary results

```{julia}
#| echo: false
#| warning: false
#| message: false
#| output: asis

cap = """
Biological values and rates for demersal fish and demersal fish larvae guilds when modelled for 2010-2019 (and 2060-2069 for larvae) using GFDL-ESM4 and CNRM-CM6-1-HR StrathE2E models under SSP3-7.0. Values represent the outputs from the final model year after running to steady state. `T_uptake` represents the total uptake of nitrogen by the guild. `T_defec_excr` represents the total nitrogen output by the guild as a result of metabolism and excretion. `Recruitment` represents the total nitrogen gained through recruitment of larvae to adults. `Spawning` represents the total nitrogen gained through spawning. `Net_Prod_feeding` represents conversion rate of nitrogen ingested to mass, less nitrogen lost through excretion (T_uptake - T_defec_excr). `Net_Prod` represents the total rate of nitrogen gained including recruitment and spawning processes (Recruitment + Spawning + Net_Prod_feeding). Recruitment reliance can be seen where `Recruitment` contributes greater mass to the guild than `T_uptake`.
"""
using Markdown, Tables, MarkdownTables, CSV, DataFrames, Format
cd("../src")
dfish_rates = CSV.read("./../outputs/initial_runs/demersal_fish_rates_variants_filtered.csv", DataFrame)
for col in names(dfish_rates)[names(dfish_rates) .!= "Rate"]
    dfish_rates[!, col] = Format.format.(dfish_rates[:, col]; precision=3, positivespace=true)
end
print(
    """
    ::: {.table #stbl-dfish-biology}
    $(markdown_table(dfish_rates, String))

    $(cap)
    :::
    """
)
```

![Guild final year, whole - domain, nitrogen mass conditions for each decade of forcing data
under each future scenario. The y axis represents the mean final year nitrogen mass in
millimoles of Nitrogen per gram of wet weight for each guild type. The x axis represents the
modelled decades. The line colours represent the two climate models, GFDL-ESM4 in blue and
CNRM-CM6-1-HR in yellow. Linestyles represent the two Shared Socio-Economic Pathways,
SSP1-2.6 with solid lines and SSP3-7.0 with dashed lines. Shaded bands represent the 95%
credible intervals for output variables obtained from Monte Carlo
simulations.](../figs/initial_cc_assessment/biomass_timeseries_mc.png){#sfig-biomass-timeseries
width="14.82cm"}

![Angles (in degrees) between guild biomass PC loadings and the vectors that summarise
ecosystem variance across NEMO-ERSEM forcing models (left) and decades (right). Angles
represent the contribution of the guild to ecosystem variance across these levels. An angle
of 0° to the decadal variation vector means a guild varies only across decades, whereas an
angle of 90° to the decadal variation vector means a guild does not vary across decades.
Angles displayed are calculated using PC loadings and variance vectors (NEMO-ERSEM forcing
model variance vector and decade variance vector) displayed in @fig-biomass-pca; Panel B.
Red lines indicate the 30° angle cutoff used for further
assessments.](../figs/initial_cc_assessment/decade_esm_separation_quantified.png){#sfig-pca-separation
width="14.82cm"}

![PCA results (as displayed in @fig-biomass-pca) for final year mass conditions for each
decade of forcing data under each future scenario and NEMO-ERSEM forcing model. The line
colours represent the two climate models, GFDL-ESM4 in blue and CNRM-CM6-1-HR in yellow.
Linestyles represent the two Shared Socio-Economic Pathways, SSP1-2.6 with solid lines and
SSP3-7.0 with dashed lines. Dot points represent 2010-2019 decade of forcing, and arrowheads
represent the 2060-2069 decade of forcing. Polygons represent ecosystem mass 95% credible
intervals generated from Monte Carlo parameter simulations, projected into median PC
space.](../figs/initial_cc_assessment/biomass_pca_mc.png){#sfig-biomass-pca-mc
width="14.82cm"}

![Distribution of residual interaction effects between environmental variables based on mass
percentage change from the 2010-2019 to 2060-2069 decades. Variable interaction effect
values around 0 mean that the interaction between variable $x$ and $y$ does not contribute
any additional effect to the output beyond the individual effects of $x + y$. The 1260
interaction values are collated across 15 'guilds' (including Net Primary Production) and 2
NEMO-ERSEM forcing models, 2 Shared Socio-Economic Pathways with 7 environmental variable
groups. Blue lines indicate the 2.5 and 97.5 percentile interaction effect
values.](../figs/across_decade_permutations/variable_interaction_histogram.png){#sfig-var-interaction-hist
width="10cm"}

![Monthly timeseries (decadal averages) of environmental driving data for variables in the
light driver group (sslight - daily integrated sea surface irradiance). Values indicate
levels of each irradiance across 12 months of the year. Blue lines represent GFDL-ESM4
NEMO-ERSEM data and yellow lines represent CNRM-CM6-1-HR NEMO-ERSEM data. Solid lines
represent SSP1-2.6 data and dashed lines represent SSP3-7.0
data.](../figs/env_drivers/light_driver_timeseries.png){#sfig-driver-light width="14.82cm"}

![Monthly timeseries (decadal averages) of environmental driving data for variables in the
river outputs driver group (rivammonia - flow weighted ammonia concentration of river
outputs, rivnitrate - flow weighted nitrate concentration of river outputs, rivervol - daily
river outflow into the inshore zone). Values indicate levels of each driving variable across
12 months of the year. Blue lines represent GFDL-ESM4 NEMO-ERSEM data and yellow lines
represent CNRM-CM6-1-HR NEMO-ERSEM data. Solid lines represent SSP1-2.6 data and dashed
lines represent SSP3-7.0
data.](../figs/env_drivers/river_outputs_driver_timeseries.png){#sfig-driver-river
width="14.82cm"}

![Monthly timeseries (decadal averages) of environmental driving data for variables in the
temperature driver group (d_temp - deep layer temperature, si_temp - shallow layer inshore
temperature, so_temp - shallow layer offshore temperature). Values indicate levels of each
driving variable across 12 months of the year. Blue lines represent GFDL-ESM4 NEMO-ERSEM
data and yellow lines represent CNRM-CM6-1-HR NEMO-ERSEM data. Solid lines represent
SSP1-2.6 data and dashed lines represent SSP3-7.0
data.](../figs/env_drivers/temperature_driver_timeseries.png){#sfig-driver-temp
width="14.82cm"}

![Monthly timeseries (decadal averages) of environmental driving data for variables in the
vertical mixing driver group. Variable names: d_so_upwelling - upwelling of water from the
deep layer to the shallow offshore compartment, logkvert - Log10 vertical diffusion
coefficient at the interface between the deep and shallow offshore layers,
so_d_downwelling - downwelling of water from the shallow offshore compartment to the deep
layer. Values indicate levels of each driving variable across 12 months of the year. Blue
lines represent GFDL-ESM4 NEMO-ERSEM data and yellow lines represent CNRM-CM6-1-HR
NEMO-ERSEM data. Solid lines represent SSP1-2.6 data and dashed lines represent SSP3-7.0
data.](../figs/env_drivers/vertical_mixing_driver_timeseries.png){#sfig-driver-vertical-mixing
width="14.82cm"}

![Monthly timeseries (decadal averages) of environmental driving data for variables in the
boundary flows driver group (d_inflow - inflow of water from external sources into the deep
layer, si_inflow - inflow of water from external sources into the shallow layer inshore
compartment, si_outflow - outflow of water from the shallow layer inshore compartment to
external water masses, so_inflow - inflow of water from external sources into the shallow
layer offshore compartment, so_si_inflow - horizontal flow of water from the offshore to
inshore shallow layer.). Values indicate levels of each driving variable across 12 months of
the year. Blue lines represent GFDL-ESM4 NEMO-ERSEM data and yellow lines represent
CNRM-CM6-1-HR NEMO-ERSEM data. Solid lines represent SSP1-2.6 data and dashed lines
represent SSP3-7.0
data.](../figs/env_drivers/boundary_flows_driver_timeseries.png){#sfig-driver-boundary-flows
width="14.82cm"}

![Monthly timeseries (decadal averages) of environmental driving data for variables in the
nutrient concentrations driver group (si - shallow inshore water volume, so - shallow
offshore volume, d - deep volume). Nutrient concentrations represent flow weighted
concentrations at the ocean boundaries of the respective model water volumes. Values
indicate levels of each driving variable across 12 months of the year. Blue lines represent
GFDL-ESM4 NEMO-ERSEM data and yellow lines represent CNRM-CM6-1-HR NEMO-ERSEM data. Solid
lines represent SSP1-2.6 data and dashed lines represent SSP3-7.0
data.](../figs/env_drivers/nutrient_concentrations_driver_timeseries.png){#sfig-driver-nutrient
width="14.82cm"}

![Monthly timeseries (decadal averages) of environmental driving data for variables in the
atmospheric nutrient flux driver group (si - shallow inshore water volume, so - shallow
offshore water volume). Flux values represent the atmospheric deposition rate of nitrate and
ammonia into the inshore and offshore zones. Values indicate levels of each driving variable
across 12 months of the year. Blue lines represent GFDL-ESM4 NEMO-ERSEM data and yellow
lines represent CNRM-CM6-1-HR NEMO-ERSEM data. Solid lines represent SSP1-2.6 data and
dashed lines represent SSP3-7.0 data. Atmospheric nutrient flux data do not vary across the
NEMO-ERSEM forcing models, so appear as a single set of solid and dashed
lines.](../figs/env_drivers/atmospheric_nutrient_flux_driver_timeseries.png){#sfig-driver-atmospheric_nutrient
width="14.82cm"}

![Coefficient of variation values for each driving variable across decades (left) and across
NEMO-ERSEM forcing models (right). Coefficients of variation are calculated based on monthly
values using the annual variance averaged across the remaining analysis levels (averaged
across SSPs and NEMO-ERSEM forcing models for across decade values, and averaged across
decades and SSPs for across NEMO-ERSEM forcing model values). Bars are coloured by the
driver groupings used for permutation analyses. Variables in the "atmospheric nutrient flux"
group do not vary across NEMO-ERSEM forcing models so were removed from across NEMO-ERSEM
forcing model permutation
analyses.](../figs/env_drivers/driving_variable_variation.png){#sfig-driving-variable-variation
width="14.82cm"}

![Proportional sources of nitrogen influx to guilds whose PCA loadings correlate strongly
(within 30°) with ecosystem decadal trends. Diet proportions are displayed for each model
variant (six decades, two NEMO-ERSEM forcing models and two SSPs). Rows display different
decades and columns display different NEMO-ERSEM forcing model - SSP combinations. Nitrogen
sources are represented by different colours, including benthos carnivorous/scavenge feeders
(benthc), benthos suspension/deposit feeders (benths), carnivorous zooplankton (carnzoo),
corpses, demersal fish (dfish), demersal fish larvae (dfishlar), fisheries discards, kelp,
kelp debris, migratory fish (mfish), direct intake from outside of the model domain
(ocean_horizontal), omnivorous zooplankton (omnivzoo), planktivorous fish (pfsih),
planktivorous fish larvae (pfishlar), pinnipeds (seal), water column ammonia (wcammonia),
water column nitrate
(wcnitrate).](../figs/initial_cc_assessment/decade_sep_guilds_nitrogen_sources.png){#sfig-decade-sep-diet
width="14.82cm"}

![Predatory guild (including Birds, Cetaceans, Demersal fish, Demersal fish larvae and
Planktivorous fish) mass levels across ranges of demersal fish larvae physiological
parameter values. Both GFDL-ESM4 (blue) and CNRM-CM6-1-HR (yellow) parameterizations of
2010-2019 StrathE2E models are used. Parameter values are sampled from -25% to +25% of their
baseline, best-fit, values. Each response guild is represented by a column, and each
demersal fish parameter used is represented by a row. Red triangles represent the mass value
from the best-fit
model.](../figs/initial_cc_assessment/demfishlar_param_sens_unlinked.png){#sfig-dfishlar-sensitivity
width="14.82cm"}

![Decadal climatologies of daily mean wind speed (radius, $m s^{-1}$) and direction (angle)
from the two CMIP6 NEMO-ERSEM forcing models CNRM-CM6-1-HR (top row) and GFDL-ESM4 (bottom
row). The left column shows the StrathE2E baseline period (2010-2019), the middle column
shows the mid-century period (2060-2069), and the right column shows the difference in wind
bearing (0 $+/-$ 180°) between these two periods. The colour represents the day of the
climatological year from January to December. Warm colours represent austral summer and cool
colours represent austral winter. A North West wind angle represents "South Easterly" wind
fields that are favourable for upwelling in the Southern Benguela system. Projections from
SSP1-2.6 are displayed
here.](../figs/ssp126_daily_masked_smoothed_twilight_shifted_r_difference_multi.png){#sfig-ssp1-winds-cmip
width="14.82cm"}

![Decadal climatologies of daily mean wind speed (radius, $m s^{-1}$) and direction (angle)
from the two CMIP6 NEMO-ERSEM forcing models CNRM-CM6-1-HR (top row) and GFDL-ESM4 (bottom
row). The left column shows the StrathE2E baseline period (2010-2019), the middle column
shows the mid-century period (2060-2069), and the right column shows the difference in wind
bearing (0 $+/-$ 180°) between these two periods. The colour represents the day of the
climatological year from January to December. Warm colours represent austral summer and cool
colours represent austral winter. A North West wind angle represents "South Easterly" wind
fields that are favourable for upwelling in the Southern Benguela system. Projections from
SSP3-7.0 are displayed
here.](../figs/ssp370_daily_masked_smoothed_twilight_shifted_r_difference_multi.png){#sfig-ssp3-winds-cmip
width="14.82cm"}

![Shapley Effect contribution values for guilds that were not identified as being strongly
correlated with ecosystem state change over time (@sfig-pca-separation) under each forcing
model - SSP scenario. Bars represent the contribution of each driver group to guild mass
variance, with a value of 1 representing explanation of 100% of guild variance. Variables
are represented by different colours, with a lack of colour indicating no contribution of
output variance (no contribution from light, river outputs, nutrient concentrations or
atmospheric nutrient flux driver groups). Blue bars indicate the contribution of boundary
flow variables; orange bars represent the contribution of temperature variables and green
bars indicate the contribution of vertical mixing variables to guild output
variance.](../figs/across_decade_permutations/important_guild_shapley_other_guilds.png){#sfig-across-decade-shap-others
width="14.82cm"}

![Shapley Effect contribution values for guilds not identified as being strongly correlated
with differences in ecosystem state across the NEMO-ERSEM forcing models
(@sfig-pca-separation), for each StrathE2E parameterization. Points represent the median
Shapley Effect value for each guild and driver group across the combinations of two SSPs and
six decades. Error bars represent the interquartile range of Shapley Effect values for each
guild and driver group. As median and interquartile range values are displayed, effects for
a guild may not sum to
1.](../figs/across_esm_permutations/median_shapley_effects_other_guilds.png){#sfig-across-esm-shap-others
width="14.82cm"}